%% Part 1: Generation of an AR)1) processs
clear
%% AR(1) with correlation coefficients a = 0.98
% Generate the AR(1) process and show the input and output of the model
for irealiz = 1:10
    N = 2000;
    a = 0.98;
    e  = randn(N,1); % white noise of zero mean
    y1 = 0.;
    for ii = 2:N
        y1(ii) = a * y1(ii-1) + e(ii); % generate the AR(1) process
    end
    figure(1)
    subplot(211)
    plot(1:N,e(1:N))
    title('Input: white noise','Fontsize',20)
    xlabel('time t','Fontsize',16)
    ylabel('e_t','Fontsize',16)
    subplot(212)
    plot(1:N,y1)
    title(['Output: AR(1), a = ' num2str(a)] ,'Fontsize',20)
    xlabel('time t','Fontsize',16)
    ylabel('y_t','Fontsize',16)
    mean_std_max(irealiz,1:6) = [mean(y1(1:300)), std(y1(1:300)) max(abs(y1(1:300))) ...
                                   mean(y1(300:end)), std(y1(300:end)) max(abs(y1(300:end)))];
    meanc(irealiz)=  mean(y1);
end
mean(meanc)
mean_std_max
max(y1)
min(y1)
% Background hints:
% (1) a^50 = 0.36; a^225 = 0.01; a^300 = 0.002; a^2000 = 2.8324e-18;a^5000=1.3501e-44;
% (2) r_0 = sigma_e^2/(1-a^2) is the variance for stationary regim and is called here true autocorrelation
% (3) for e generated by the function randn sigma_e^2 = 1
% (4) Repeating the generation process 10 times we get some statistics
% collected in the matrix mean_std_max.
% Question:
% Which of the following statements are true? (there might be multiple correct statements)
%
% a) The input e and the output y1 are generated in such a way that their expectations
% are as follows: Ee = 0 but Ey is different of 0.
% b) We expect a transitory regim of maximum 300 samples, after which the
% process is stationary.
% c) The range of the output y is about (-20,20), because the variance sigma_y^2 = Ey_i^2 is
% 1/(1-a^2)= 25.25, the standard deviation is about sigma_y = 5, and hence we expect
% most of the time the signal to be between (-4sigma_y,+4sigma_y).
% d)  The standard deviation for the transitory part is similar to the 
% standard deviation for the stationary part.
% e) the maximum value over the transitory part is noticeably smaller than for 
% the stationary part, because the number of random points in the transitory
% parts is smaller than the number points in the permanent regim

%% Part 2: Estimate the auto-correlation function of an AR)1) processs
%% Experiment with three cases for the generated data length

N1  = [2*10^5 5*10^4 2*10^4];%  three values for the length of data
% a = 0.98  is high, but not extremely close to 1
a  = 0.98; % a is also called the correlation coefficient

max_tau = 2000; % we estimate r(0),r(1),...,r(max_tau)

% The analytic expression of the autocorrelation function
r_true(1+(0:max_tau)) = (a.^(0:max_tau))/(1-a^2);

colors  = ['r-';'g-';'m-';'b-']
figure(2), clf,plot(0:max_tau,r_true,'b-'), hold on

for len = 1:3 
    N = N1(len);        % Maximum value of discrete time
    % Nt = floor(N/4);  % The time series is cropped from Nt,Nt+1,..., N
    Nt = 2*10^4/4;      % Let's neglect the same initial segment, 1...Nt, for all three cases
    e  = randn(N,1);
    y1 = 0.;
    
    for ii = 2:N
        y1(ii) = a*y1(ii-1) + e(ii); % generate the AR(1) process
    end
    y = y1(Nt:N);
    Ny = length(y);
    %
    % Estimate the autocorrelation function from data, knowing that Ey = 0
    %
    r = zeros(max_tau+1,1);
    for tau = 0:max_tau
        % if(rem(tau,100)==0),[tau max_tau],end % show the iteration progressing
        time_segment = 1:(Ny-tau);
        r(tau+1) = sum(y(time_segment).* y(tau+time_segment))/(Ny-tau);
    end
    %
    plot(0:max_tau,r,colors(len,:))
end
title(['Autocorrelation function, a = ' num2str(a)],'Fontsize',14)
xlabel('lag \tau','Fontsize',12)
ylabel('r(\tau)','Fontsize',12)
legend('true r','N=2000000','N=200000','N=20000')  

%% Question
% Background
% We consider here the following helpful results, proven in the pdf for
% this task
% (1) a^50 = 0.36; a^225 = 0.01; a^2000 = 2.8324e-18; a^5000=1.3501e-44;
% (2) Ey_ny_{n-k} = a^k*(1-a^{2n-2k})/(1-a^2)
% (3) In the stationary regim r_k = a^k/(1-a^2), which  is called here true
%       autocorrelation
%
% Question 1: State which of the following statements are true:
% a) For the first 50 correlation values the estimates are  reasonably close to the
% true value, for all three cases of N
% b) for the case N = 2*10^4 the estimates for large lags tau are not
% reliable, because there are not enough data points 
% c) The efect of non-stationarity shown in (2) makes the estimates at low
% N unreliable

%% Part 3: Discuss the effect of accuracy of estimating the autocorrelation 
%% function for the adaptive noise cancellation (ANC) application
% In the ANC, the Wiener-Hopf optimal filter design requires the inversion
% of the correlation matrix. The needed order of the filter might be quite
% large for ANC (from hudreads to thousands, as you estimated it in Lecture 1,
% bonus assignment)
%
% Assume that in ANC the source of noise is the AR(1) process, from Part 1
% and the estimated autocorrelation was done as in Part 2, for N = 2*10^4
% Consider a filter of order 200.

%% Case 1: consider the true autocorrelation function r_true
% The autocorrelation matrix  R needed in Wiener-Hopf design w = R^(-1)p

R = toeplitz(r_true(1:200));
figure(3),imagesc(R), colormap(gray),title('Autocorrelation matrix R')
invR = inv(R);
figure(4),imagesc(invR), colormap(gray),title('Inverse of autocorrelation matrix R'),colorbar

%% Case 2: consider the estimated autocorrelation using N = 2*10^4 (Corresponding to len = 3 in Part 2)
% The autocorrelation matrix  R needed in Wiener-Hopf design w = R^(-1)p

Restim = toeplitz(r(1:200));
figure(5),imagesc(R), colormap(gray),title('Estimated utocorrelation matrix R')
invRestim = inv(Restim);
figure(6),imagesc(invRestim), colormap(gray),title('Inverse of estimated autocorrelation matrix R'),colorbar

% Questions: 
%
% Q1: Inspect the matrix inv(R). It is a band matrix, having only three 
% nonzero diagonals: the main, the first upper, and the first lower
% diagonals. Which statements are true:
% a) the first upper diagonal and the first lower diagonal are equal to -a
% b) the main diagonal has at the extremities the value 1, while the 
% rest of the elements are equal to 1+a^2
% c) the main diagonal has all the elements equal to 1+a^2
%
% Q2: The elements of the matrix R are  R(i,j) = a^(i-j)/(1-a^2), hence R is a
% Toeplitz matrix. 
% a) It is a general result that the inverse of the matrix
% with elements R(i,j) = a^(i-j)/(1-a^2) is the tridiagonal matrix
% that you described answering Question 1.
% b) The statement is not true in general, it happens to be true only for some
% particular values of a. 
%

%% Part 4: LS estimate of parameters for AR(4)
clear all;
close all;
% Choose a ground truth model AR(4)
% The roots of the AR polynomial are 
j = sqrt(-1);
z=[];
z(1)= 0.95*exp(j*pi/3);
z(2)= 0.95*exp(-j*pi/3);
z(3)= 0.75*exp(j*(pi/2+pi/3));
z(4)= 0.75*exp(-j*(pi/2+pi/3));
A = poly(z)
figure(11),clf, plot(real(z),imag(z),'bo')
title('Positions of the roots of A(z)')
axis equal
grid on
r1 = 1;
t = linspace(0,2*pi,100);
hold on
plot(r1*cos(t),r1*sin(t),'r-')
% Generate data with the AR polynomial

N = 100000;
Nt = floor(N/4);   % The time series is cropped from Nt,Nt+1,..., N
e  = randn(N,1);
y1 = zeros(N,1);

for ii = 5:N
    y1(ii) = -A(2:5)*y1((ii-1):-1:(ii-4)) + e(ii); % generate the AR(1) process
end
y = y1(Nt:end);
Ny = length(y);
%
% Estimate the autocorrelation function from data, knowing that Ey = 0
%
max_tau = 20;
r = zeros(max_tau+1,1);
for tau = 0:max_tau
    if(rem(tau,100)==0),[tau max_tau],end
    time_segment = 1:(Ny-tau);
    r(tau+1) = sum(y(time_segment).* y(tau+time_segment))/(Ny-tau);
end
% LS estimate of the AR(M) model
% y(n) = a1*y(n-1)+
Mmax = 15
thetaAll = zeros(Mmax);
for M = 1:Mmax
    % Construct the normal system matrix and free vector
    Phi = zeros(M,M); Psi = zeros(M,1);
    for n = (Mmax+1):Ny
        Phi = Phi + y((n-1):-1:(n-M))*y((n-1):-1:(n-M))';
        Psi = Psi + y((n-1):-1:(n-M))*y(n);
    end
    % Find the LS parameters
    theta = Phi\Psi;
    hat_e = zeros(Ny,1);
    for n = (Mmax+1):Ny
        hat_e(n) = y(n) - theta'*y((n-1):-1:(n-M));
    end
    J(M) = mean(hat_e.^2);
    thetaAll(1:M,M) = theta;
end
thetaAll
J
A
figure(12),plot(J,'or-'),grid on
xlabel('Order M')
ylabel('Criterion J(M)')
%% Questions     
% Q1: Compare the LS parameter thetaAll(:,4) with the AR  polynomial given
% in A. What is true?
% a) The LS estimates are erronues
% b) The LS estimates are close to the true values of the AR process
%
% Q2: Determine visually from Figure 12 what is the true order of
% the AR process:
% a) M^* = 4
% b) M^* = 1
% c) M^* = 5
        
%% Part 5: Three structure selection criteria: FPE against AIC against MDL

% FPE
% Consider FPE = ((N+k)/(N-k))*sigma2
% log FPE = log((N+k)/(N-k)) + log(sigma2)
% AIC
% AIC = N*log(sigma2) + 2*k
% AIC/N = log(sigma2) + 2*k/N
% MDL = N*log(sigma2) + k*log(N)
% MDL/N = log(sigma2) + k*log(N)/N

% Penalty in log(FPE) is log((N+k)/(N-k)) = log((1+k/N)/(1-k/N)) \approx
% (k/N)-(-k/N) = 2*k/N
% Penalty in AIC/N  is 2*k/N
% Task: plot the penalty terms in both expressions and compare
N = 101;
k = 1:(N-1);
figure(20),plot(k,log((N+k)./(N-k)),'or-',k, 2*k/N,'b-', k, k*log(N)/N,'g-'),xlabel('k'),ylabel('Penalty term')
legend('Penalty in log(FPE)', 'Penalty in AIC/N', 'Penalty in MDL/N'),grid on

%% Question:
%
% Q1: Which of the following statements are true?
% a) Out of all three criteria, MDL criterion penalizes the most the increase of k, so it will decide smaller orders than the others
% b) Out of all three criteria, FPE criterion penalizes the most the increase of k, so it will decide smaller orders than the others criteria

%% Use the three structure selection criteria for the AR(1),...,AR(15) models obtained  in Part 4
% in the previou s 
Crit1 = log(J) + log((Ny+(1:15))./(Ny-(1:15)));
Crit2 = log(J) + 2*(1:15)/Ny;
Crit3 = log(J) + (1:15)*log(Ny)/Ny;
figure(21), plot( 1:15, Crit1,'or-', 1:15, Crit2,'og-', 1:15, Crit3, 'ob-')
format shortg
[Crit1'  Crit2' Crit3']

% Q2: Consider the values of Crit1, Crti 2, and Crit 3. Each criterion is 
% used for picking the best mode order. In this case, which of the methods 
% selects the correct model order?
% a)FPE; b) AIC; c)MDL (multiple possible correct answers)
%
 